export const skills = [
  {
    id: 16000,
    name: "Basic Attack",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16010,
    name: "Fist Attack",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16020,
    name: "Basic Attack",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16080,
    name: "Hell Blade",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16170,
    name: "Hell Blade Temp",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16100,
    name: "Double Slash",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16090,
    name: "Strike Wave",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16070,
    name: "Whirlwind",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16130,
    name: "Burst",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16131,
    name: "폭주 흑화 광기 각인",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16132,
    name: "폭주 흑화 광기 각인 해제",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16050,
    name: "Crime Hazard",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16160,
    name: "Theatric Combat Switch",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16060,
    name: "Shoulder Charge",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16061,
    name: "Shoulder Charge",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16030,
    name: "Power Break",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16110,
    name: "Assault Blade",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16150,
    name: "Charge Strike",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16180,
    name: "Hell Blade Temp",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16120,
    name: "Red Dust",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16181,
    name: "Hell Blade Temp",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16040,
    name: "Tumbling",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16140,
    name: "Bloody Rush",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16190,
    name: "Tempest Slash",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16210,
    name: "Diving Slash",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16300,
    name: "Finish Strike",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16045,
    name: "Stand Up",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16046,
    name: "Stand Up",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16220,
    name: "Mountain Crash",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16400,
    name: "Aura Blade",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16500,
    name: "Chain Sword",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16600,
    name: "Sword Storm",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16700,
    name: "Chain of Vengeance",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16610,
    name: "Wind Blade",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16620,
    name: "Maelstrom",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16710,
    name: "Berserk Fury",
    class: "Berserker",
    level: 0,
  },
  {
    id: 16141,
    name: "Dark Rush",
    class: "Berserker",
    level: 0,
    icon: true,
  },
  {
    id: 18000,
    name: "Basic 3 Chain Hits",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18030,
    name: "Hypergravity Basic Attack",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18050,
    name: "Heavy Crush",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18060,
    name: "Gravity Impact",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18100,
    name: "Neutralizer",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18110,
    name: "Dreadnaught",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18020,
    name: "Run",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18080,
    name: "Earth Smasher",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18090,
    name: "One-Man Army",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18070,
    name: "Full Swing",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18120,
    name: "Terra Break",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18140,
    name: "Endure Pain",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18130,
    name: "Seismic Hammer",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18150,
    name: "Earth Eater",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18160,
    name: "Jumping Smash",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18170,
    name: "Perfect Swing",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18180,
    name: "Power Strike",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18190,
    name: "Gravity Compression",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18210,
    name: "Running Crash",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18200,
    name: "Gravity Force",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18201,
    name: "Gravity Force",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18220,
    name: "Power Shoulder",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18025,
    name: "Stand Up",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18026,
    name: "Stand Up",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18011,
    name: "Vortex Gravity",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18230,
    name: "Big Bang",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 18010,
    name: "Activate Hypergravity",
    class: "Destroyer",
    level: 0,
  },
  {
    id: 17000,
    name: "Basic Attack 3 Combo Hits",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17010,
    name: "Fist Attack 3 Chain Hits",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17040,
    name: "Bash",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17060,
    name: "Fire Bullet",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17050,
    name: "Shield Charge",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17110,
    name: "Leap Attack",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17080,
    name: "Dash Upper Fire",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17200,
    name: "Surge Cannon",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17020,
    name: "Back Step",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17180,
    name: "Shout of Hatred",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17130,
    name: "Nellasia's Energy",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17140,
    name: "Guardian's Thunderbolt",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17090,
    name: "Hook Chain",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17100,
    name: "Shield Shock",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17101,
    name: "Shield Shock",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17030,
    name: "Sharp Gunlance",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17070,
    name: "Rising Gunlance",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17025,
    name: "Stand Up",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17026,
    name: "Stand Up",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17150,
    name: "Shield Bash",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17160,
    name: "Gunlance Shot",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17170,
    name: "Guardian's Protection",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17190,
    name: "Counter Gunlance",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17210,
    name: "Charged Stinger",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17800,
    name: "Defensive Stance",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17820,
    name: "Battlefield Shield",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 17220,
    name: "Lance of Judgment",
    class: "Gunlancer",
    level: 0,
  },
  {
    id: 36000,
    name: "Basic Attack",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36001,
    name: "Heavenly Guardian Basic Attack",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36010,
    name: "Unarmed Basic Attack",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36030,
    name: "Spin Slash",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36040,
    name: "Flash Thrust",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36050,
    name: "Light Shock",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36060,
    name: "Light of Judgment",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36070,
    name: "Charge",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36080,
    name: "Sword of Justice",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36090,
    name: "Flash Shash",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36100,
    name: "Holy Explosion",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36110,
    name: "Punishment",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36120,
    name: "Holy Area",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36130,
    name: "Dash Slash",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36140,
    name: "Holy Protection",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36150,
    name: "Godsent Law",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36160,
    name: "Executor's Sword",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36170,
    name: "Wrath of God",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36180,
    name: "Execution of Justice",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36190,
    name: "Holy Sword",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36200,
    name: "Heavenly Blessings",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36210,
    name: "Alithanes's Judgment",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36220,
    name: "Alithanes's Light",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36900,
    name: "Sacred Executioner",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36910,
    name: "Sacred Executioner",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36800,
    name: "Holy Aura",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36810,
    name: "신성의 오라 종료",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36025,
    name: "Stand Up",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36026,
    name: "PvP Forced Wakeup",
    class: "Paladin",
    level: 0,
  },
  {
    id: 36020,
    name: "Sprint",
    class: "Paladin",
    level: 0,
  },
  {
    id: 19030,
    name: "Evoke",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19090,
    name: "Ghost",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19300,
    name: "Evoke",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19092,
    name: "Moon",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19290,
    name: "Evoke",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19040,
    name: "Checkmate",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19098,
    name: "Judgment",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19050,
    name: "Dark Resurrection",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19093,
    name: "Corrosion",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19094,
    name: "Star",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19150,
    name: "Stream of Edge",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19095,
    name: "Wheel of Fortune",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19140,
    name: "Celestial Rain",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19096,
    name: "Royal",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19160,
    name: "Four of a Kind",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19097,
    name: "Three-Headed Snake",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19120,
    name: "Unlimited Shuffle",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19170,
    name: "Quadra Accelerate",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19281,
    name: "Cull",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19099,
    name: "Balance",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19180,
    name: "Call of Destiny",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19200,
    name: "Dancing of Spineflower",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19280,
    name: "Mayhem",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19091,
    name: "Twisted Fate",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19282,
    name: "Emperor",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19190,
    name: "Spiral Edge",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19195,
    name: "Spiral Edge",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19283,
    name: "Empress",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19260,
    name: "Return",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19110,
    name: "Prismatic Mirror",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19210,
    name: "Mysterious Stampede",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19215,
    name: "Mysterious Stampede",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19230,
    name: "Infinity Shower",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19240,
    name: "Serendipity",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19105,
    name: "Stand Up",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19106,
    name: "Stand Up",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19100,
    name: "Vanish",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19310,
    name: "Secret Garden",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19320,
    name: "Scratch Dealer",
    class: "Arcana",
    level: 0,
  },
  {
    id: 19330,
    name: "Deathbound",
    class: "Arcana",
    level: 0,
  },
  {
    id: 20291,
    name: "Kelsion",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20292,
    name: "Kelsion",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20293,
    name: "Kelsion",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20020,
    name: "Crystalline Magick",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20030,
    name: "Steed Charge",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20180,
    name: "Sticky Moss Swamp",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20040,
    name: "Reine's Protection",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20050,
    name: "Flash Explosion",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20051,
    name: "Flash Explosion",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20060,
    name: "Fleeting Gale Bird",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20210,
    name: "Elemental Wings",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20170,
    name: "Osh",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20070,
    name: "Alimaji",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20080,
    name: "Jahia & Ligheas",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20200,
    name: "Released Will",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20220,
    name: "Winged Spirit",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20230,
    name: "Electricity Release",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20231,
    name: "Electricity Release",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20240,
    name: "Earth Collapse",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20250,
    name: "Water Elemental",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20260,
    name: "Ancient Spear",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20270,
    name: "Electric Storm",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20280,
    name: "Phoenix",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20290,
    name: "Kelsion",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20160,
    name: "Shurdi",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20215,
    name: "Stand Up",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20216,
    name: "Stand Up",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20125,
    name: "Pauru - Self-Destruct",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20335,
    name: "Pauru - Self-Destruct",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20137,
    name: "Maririn - Taunt",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20138,
    name: "Maririn - Charge",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20139,
    name: "Maririn - Stagger",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20294,
    name: "Kelsion - Thunderstroke",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20120,
    name: "Pauru - Flame Breath",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20300,
    name: "Bagron's Wrath",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20310,
    name: "Akir",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20090,
    name: "Elcid",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20110,
    name: "Pauru",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20330,
    name: "Pauru - Flame Breath",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20130,
    name: "Maririn",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20347,
    name: "Maririn - Taunt",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20348,
    name: "Maririn - Charge",
    class: "Summoner",
    level: 0,
  },
  {
    id: 20349,
    name: "Maririn - Stagger",
    class: "Summoner",
    level: 0,
  },
  {
    id: 21020,
    name: "Sound Shock",
    class: "Bard",
    level: 0,
  },
  {
    id: 21040,
    name: "Conviction Core",
    class: "Bard",
    level: 0,
  },
  {
    id: 21050,
    name: "Sound Wave",
    class: "Bard",
    level: 0,
  },
  {
    id: 21060,
    name: "Dissonance",
    class: "Bard",
    level: 0,
  },
  {
    id: 21070,
    name: "Wind of Music",
    class: "Bard",
    level: 0,
  },
  {
    id: 21079,
    name: "Wind of Music",
    class: "Bard",
    level: 0,
  },
  {
    id: 21080,
    name: "Prelude of Storm",
    class: "Bard",
    level: 0,
  },
  {
    id: 21090,
    name: "Stigma",
    class: "Bard",
    level: 0,
  },
  {
    id: 21150,
    name: "Rhythm Buckshot",
    class: "Bard",
    level: 0,
  },
  {
    id: 21110,
    name: "Note Bundle",
    class: "Bard",
    level: 0,
  },
  {
    id: 21120,
    name: "Soundholic",
    class: "Bard",
    level: 0,
  },
  {
    id: 21160,
    name: "Heavenly Tune",
    class: "Bard",
    level: 0,
  },
  {
    id: 21170,
    name: "Sonic Vibration",
    class: "Bard",
    level: 0,
  },
  {
    id: 21130,
    name: "Serenade of Salvation",
    class: "Bard",
    level: 0,
  },
  {
    id: 21131,
    name: "Serenade of Salvation",
    class: "Bard",
    level: 0,
  },
  {
    id: 21132,
    name: "Serenade of Salvation",
    class: "Bard",
    level: 0,
  },
  {
    id: 21133,
    name: "Serenade of Salvation",
    class: "Bard",
    level: 0,
  },
  {
    id: 21100,
    name: "Sound Illusion",
    class: "Bard",
    level: 0,
  },
  {
    id: 21215,
    name: "Stand Up",
    class: "Bard",
    level: 0,
  },
  {
    id: 21216,
    name: "Stand Up",
    class: "Bard",
    level: 0,
  },
  {
    id: 21180,
    name: "Harp of Rhythm",
    class: "Bard",
    level: 0,
  },
  {
    id: 21140,
    name: "Serenade of Courage",
    class: "Bard",
    level: 0,
  },
  {
    id: 21141,
    name: "Serenade of Courage",
    class: "Bard",
    level: 0,
  },
  {
    id: 21142,
    name: "Serenade of Courage",
    class: "Bard",
    level: 0,
  },
  {
    id: 21143,
    name: "Serenade of Courage",
    class: "Bard",
    level: 0,
  },
  {
    id: 21240,
    name: "Prelude of Death",
    class: "Bard",
    level: 0,
  },
  {
    id: 21250,
    name: "Guardian Tune",
    class: "Bard",
    level: 0,
  },
  {
    id: 21260,
    name: "Rhapsody of Light",
    class: "Bard",
    level: 0,
  },
  {
    id: 21230,
    name: "Symphonia",
    class: "Bard",
    level: 0,
  },
  {
    id: 21270,
    name: "March",
    class: "Bard",
    level: 0,
  },
  {
    id: 21280,
    name: "Oratorio",
    class: "Bard",
    level: 0,
  },
  {
    id: 37000,
    name: "[소서리스] 기본 공격",
    display: "Basic Attack",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37010,
    name: "[소서리스] 맨손 평타",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37020,
    name: "Phase Leap",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37030,
    name: "Stand Up",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37040,
    name: "Stand Up",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37200,
    name: "Blaze",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37230,
    name: "Inferno",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37330,
    name: "Explosion",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37350,
    name: "Doomsday",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37220,
    name: "Ice Shower",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37250,
    name: "Rime Arrow",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37340,
    name: "Frost's Call",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37341,
    name: "Frost's Call",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37290,
    name: "Elegian's Touch",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37291,
    name: "Elegian's Touch",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37320,
    name: "Seraphic Hail",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37210,
    name: "Lightning Vortex",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37211,
    name: "[소서리스][라이트닝 볼텍스][7번] 체인 스킬",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37300,
    name: "Lightning Bolt",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37270,
    name: "Punishing Strike",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37240,
    name: "Energy Discharge",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37280,
    name: "Reverse Gravity",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37310,
    name: "Squall",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37260,
    name: "Esoteric Reaction",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37100,
    name: "Arcane Rupture",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37101,
    name: "Arcane Rupture",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37102,
    name: "[소서리스][아이덴티티티] 마력 방출 (z 스킬 off)",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37110,
    name: "Blink",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37360,
    name: "Enviska's Might",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 37370,
    name: "Apocalypse Call",
    class: "Sorceress",
    level: 0,
  },
  {
    id: 22100,
    name: "Esoteric Skill: Lightning Strike",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22020,
    name: "Esoteric Skill: Blast Formation",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22070,
    name: "Sleeping Ascent Celebration",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22060,
    name: "Flash Heat Fang",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22080,
    name: "Roar of Courage",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22040,
    name: "Esoteric Skill: Rising Fire Dragon",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22180,
    name: "Triple Fist",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22120,
    name: "Wind's Whisper",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22110,
    name: "Esoteric Skill: Call of the Wind God",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22090,
    name: "Seismic Strike",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22030,
    name: "Esoteric Skill: Spiral Impact",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22130,
    name: "Phoenix Advent",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22160,
    name: "Sky Shattering Blow",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22150,
    name: "Charging Steps",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22190,
    name: "Moon Flash Kick",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22170,
    name: "Lightning Kick",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22155,
    name: "Stand Up",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22156,
    name: "Stand Up",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22280,
    name: "Swift Wind Kick",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22290,
    name: "Energy Combustion",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22310,
    name: "Ultimate Skill: Flash Rage Blow",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22320,
    name: "Sweeping Kick",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 22330,
    name: "Ultimate Skill: Fist of Dominance",
    class: "Wardancer",
    level: 0,
  },
  {
    id: 23020,
    name: "Charging Blow",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23080,
    name: "Chain of Resonance",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23090,
    name: "Crushing Smite",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23100,
    name: "Chain Destruction Fist",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23050,
    name: "Dragon Advent",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23210,
    name: "Critical Blow",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23070,
    name: "Earthquake Chain",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23060,
    name: "Judgment",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23110,
    name: "Death Rattle",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23130,
    name: "Supernova",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23160,
    name: "Roundup Sweep",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23150,
    name: "Instant Hit",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23180,
    name: "Fierce Tiger Strike",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23200,
    name: "Continuous Push",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23170,
    name: "Duck",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23171,
    name: "Duck",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23172,
    name: "Duck",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23175,
    name: "Stand Up",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23176,
    name: "Stand Up",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23220,
    name: "Battering Fists",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23230,
    name: "Iron Cannon Blow",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23240,
    name: "True Rising Fist",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23250,
    name: "Undefeated Dragon King",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23260,
    name: "Shredding Strike",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 23270,
    name: "Mysterious Art: Blast of Ruination",
    class: "Scrapper",
    level: 0,
  },
  {
    id: 24090,
    name: "Energy Bullet",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24040,
    name: "Energy Blast",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24050,
    name: "World Decimation",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24070,
    name: "Venomous Fist",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24080,
    name: "Lightning Palm",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24210,
    name: "Merciless Pummel",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24110,
    name: "Palm Burst",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24120,
    name: "Heavenly Squash",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24140,
    name: "Crippling Barrier",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24150,
    name: "Nebulous Step",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24170,
    name: "Magnetic Palm",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24180,
    name: "Pulverizing Palm",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24190,
    name: "Tempest Blast",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24200,
    name: "Shadowbreaker",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24155,
    name: "Stand Up",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24156,
    name: "Stand Up",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24220,
    name: "Bolting Crash",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24230,
    name: "Force Orb",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24240,
    name: "Flash Step",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24241,
    name: "Flash Step",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24242,
    name: "Flash Step",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24250,
    name: "Energy Release",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24020,
    name: "Hype",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24021,
    name: "Level 2 Hype",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24022,
    name: "Level 3 Hype",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24023,
    name: "Level 3 Hype",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24260,
    name: "Deadly Finger",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 24270,
    name: "Decimation Ray",
    class: "Soulfist",
    level: 0,
  },
  {
    id: 34500,
    name: "Flurry Stance",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34501,
    name: "Flurry Stance",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34000,
    name: "Focus Stance",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34001,
    name: "Focus Stance",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34020,
    name: "Mirage Dash",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34030,
    name: "Stand Up",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34031,
    name: "Stand Up",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34040,
    name: "Double Strike",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34050,
    name: "Windsplitter",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34060,
    name: "Stampeding Slash",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34061,
    name: "Stampeding Slash",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34070,
    name: "Wheel of Blades",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34080,
    name: "Flash Kick",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34090,
    name: "Vault",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34100,
    name: "Blue Dragon's Claw",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34110,
    name: "Half Moon Slash",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34120,
    name: "Chain Slash",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34130,
    name: "Cutting Wind",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34150,
    name: "Raging Dragon Slash",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34140,
    name: "Soul Cutter",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34160,
    name: "Spear Dive",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34170,
    name: "Shackling Blue Dragon",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34520,
    name: "Breakthrough",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34540,
    name: "Spiraling Spear",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34550,
    name: "4-Headed Dragon",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34560,
    name: "Thrust of Destruction",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34570,
    name: "Starfall Pounce",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34580,
    name: "Dragonscale Defense",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34590,
    name: "Red Dragon's Horn",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34600,
    name: "Yeon-Style Spear Technique: Spear Meteor",
    class: "Glavier",
    level: 0,
  },
  {
    id: 34610,
    name: "Yeon-Style Spear Technique: Storming Red Dragon",
    class: "Glavier",
    level: 0,
  },
  {
    id: 25040,
    name: "Surprise Attack",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25060,
    name: "Upper Slash",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25100,
    name: "Blade Dance",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25070,
    name: "Earth Cleaver",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25080,
    name: "Death Sentence",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25090,
    name: "Twin Shadows",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25093,
    name: "Twin Shadows",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25050,
    name: "Wind Cut",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25110,
    name: "Soul Absorber",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25120,
    name: "Spincutter",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25130,
    name: "Turning Slash",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25140,
    name: "Moonlight Sonic",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25150,
    name: "Dark Axel",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25160,
    name: "Maelstrom",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25170,
    name: "Polestar",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25180,
    name: "Void Strike",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25190,
    name: "Fatal Wave",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25200,
    name: "Blitz Rush",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25210,
    name: "Head Hunt",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25300,
    name: "Flash Blink",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25350,
    name: "Blade Assault",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25030,
    name: "Death Trance",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25031,
    name: "Death Trance",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25032,
    name: "Death Trance",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25035,
    name: "Level 1",
    display: "Surge",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25036,
    name: "Level 2",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25037,
    name: "Level 3",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25038,
    name: "Zero",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25020,
    name: "High-Speed Move",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 25025,
    name: "Stand Up",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 27020,
    name: "Rush",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27800,
    name: "Basic Attack",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27025,
    name: "Stand Up",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27026,
    name: "Stand Up",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27870,
    name: "Stand Up",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27030,
    name: "Demonize",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27032,
    name: "Cancel Demonization",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27035,
    name: "Gate of Eruption",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27050,
    name: "Demonic Slash",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27051,
    name: "Demonic Slash",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27060,
    name: "Nimble Cut",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27070,
    name: "Slasher",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27080,
    name: "Brutal Cross",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27130,
    name: "Grind Chain",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27140,
    name: "Spinning Dive",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27250,
    name: "Sharpened Cut",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27180,
    name: "Cruel Cutter",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27200,
    name: "Thrust Impact",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27220,
    name: "Demolition",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27090,
    name: "Demon's Grip",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27100,
    name: "Rising Claw",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27110,
    name: "Piercing Thorn",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27120,
    name: "Demon Vision",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27170,
    name: "Howl",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27801,
    name: "Rift Walk",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27810,
    name: "Ruining Rush",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27820,
    name: "Death Claw",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27830,
    name: "Gore Bleeding",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27840,
    name: "Destruction",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27850,
    name: "Leaping Blow",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27860,
    name: "Blood Massacre",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27890,
    name: "Fallen Ruin",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27230,
    name: "Spinning Weapon",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27240,
    name: "Decimate",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 27210,
    name: "Demonic Clone",
    class: "Shadowhunter",
    level: 0,
  },
  {
    id: 26020,
    name: "Shadow Step",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26500,
    name: "",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26030,
    name: "Stand Up",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26031,
    name: "[리퍼] [PVP][기상액션]",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26040,
    name: "Persona",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26050,
    name: "Spinning Dagger",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26060,
    name: "Spirit Catch",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26070,
    name: "Shadow Dot",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26090,
    name: "Nightmare",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26100,
    name: "Nightmare",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26130,
    name: "Nightmare",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26080,
    name: "Iblisto",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26110,
    name: "Saber Stinger",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26120,
    name: "Death Side",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26510,
    name: "Distortion",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26520,
    name: "Blink",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26530,
    name: "Blink",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26540,
    name: "[리퍼][그림자] 블링크 소환수 명령 - 단검공격",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26610,
    name: "Blink",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26620,
    name: "[리퍼][그림자] 블링크 소환수 명령 - 전진베기",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26550,
    name: "Call of the Knife",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26560,
    name: "Black Mist",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26570,
    name: "Shadow Trap",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26590,
    name: "[리퍼][그림자] 쉐도우 트랩 7번 체인 스킬",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26800,
    name: "Last Graffiti",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26810,
    name: "Rage Spear",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26820,
    name: "Silent Smasher",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26830,
    name: "Dance of Fury",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26900,
    name: "Lunar Eclipse: Cadenza",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26910,
    name: "Solar Eclipse: Requiem",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26920,
    name: "Solar Eclipse: Requiem",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26930,
    name: "Solar Eclipse: Requiem",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26950,
    name: "Solar Eclipse: Requiem",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26600,
    name: "Shadow Storm",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26140,
    name: "Phantom Dancer",
    class: "Reaper",
    level: 0,
  },
  {
    id: 26150,
    name: "Phantom Dancer",
    class: "Reaper",
    level: 0,
  },
  {
    id: 28015,
    name: "Slide",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28159,
    name: "Silverhawk Basic Attack",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28020,
    name: "Rapid Shot",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28030,
    name: "Salvo",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28040,
    name: "Atomic Arrow",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28050,
    name: "Electric Nova",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28060,
    name: "Smokescreen Arrow",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28070,
    name: "Arrow Wave",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28080,
    name: "Arrow Shower",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28090,
    name: "Charged Shot",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28100,
    name: "Evasive Fire",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28110,
    name: "Sharp Shooter",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28120,
    name: "DM-42",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28125,
    name: "DM-42",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28130,
    name: "Deadly Slash",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28140,
    name: "Moving Slash",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28150,
    name: "Blade Storm",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28190,
    name: "Claymore Mine",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28200,
    name: "Shadow Arrow",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28210,
    name: "Stalker",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28220,
    name: "Snipe",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28157,
    name: "Summon Silverhawk",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28158,
    name: "Summon Silverhawk",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28160,
    name: "Wings of Storm",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28170,
    name: "Last Rush",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28230,
    name: "Fenrir's Messenger",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28017,
    name: "Stand Up",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 28240,
    name: "Golden Eye",
    class: "Sharpshooter",
    level: 0,
  },
  {
    id: 29100,
    name: "Meteor Stream",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29060,
    name: "Spiral Flame",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29040,
    name: "Sign of Apocalypse",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29041,
    name: "Sign of Apocalypse",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29020,
    name: "Enforce Execution",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29090,
    name: "Death Fire",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29070,
    name: "Triple Explosion",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29071,
    name: "Triple Explosion",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29072,
    name: "Triple Explosion",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29073,
    name: "Triple Explosion",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29120,
    name: "AT02 Grenade",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29180,
    name: "Spiral Tracker",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29140,
    name: "Plasma Bullet",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29080,
    name: "Catastrophe",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29150,
    name: "Tumbling",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29170,
    name: "Shotgun Rapid Fire",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29200,
    name: "Dexterous Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29190,
    name: "Cruel Tracker",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29155,
    name: "Stand Up",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29210,
    name: "Somersault Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29220,
    name: "Equilibrium",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29230,
    name: "Last Request",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29240,
    name: "Aimed Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29250,
    name: "Clay Bombardment",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29260,
    name: "Quick Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29261,
    name: "Quick Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29262,
    name: "Quick Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29110,
    name: "Shotgun Dominator",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29270,
    name: "Perfect Shot",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29280,
    name: "Bursting Flare",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29160,
    name: "Change Stance",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29161,
    name: "Change Stance",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29162,
    name: "Change Stance",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29163,
    name: "Change Stance",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29164,
    name: "Change Stance",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 29050,
    name: "Hour of Judgment",
    class: "Deadeye",
    level: 0,
  },
  {
    id: 30020,
    name: "Enter Barrage Mode",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30021,
    name: "Exit Barrage Mode",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30050,
    name: "Enhanced Shell",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30240,
    name: "Barrage: Basic Attack",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30060,
    name: "Freeze Shell",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30070,
    name: "Buckshot",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30080,
    name: "Multiple Rocket Launcher",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30090,
    name: "Howitzer",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30100,
    name: "Summon Turret",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30110,
    name: "Air Raid",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30120,
    name: "Flamethrower",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30270,
    name: "Barrage: Energy Cannon",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30140,
    name: "Swing",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30150,
    name: "Jump Barrage",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30160,
    name: "Energy Field",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30170,
    name: "Gatling Gun",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30180,
    name: "Napalm Shot",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30250,
    name: "Barrage: Howitzer",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30015,
    name: "Roll",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30155,
    name: "Stand Up",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30260,
    name: "Barrage: Focus Fire",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30190,
    name: "Forward Barrage",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30200,
    name: "Gravity Explosion",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30210,
    name: "Plasma Storm",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30220,
    name: "Homing Barrage",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30230,
    name: "Missile Barrage",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30290,
    name: "Bombardment: Impregnability",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30280,
    name: "Heavy Turret",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 30285,
    name: "Photoelectronic Cannon",
    class: "Artillerist",
    level: 0,
  },
  {
    id: 35061,
    name: "[드론] 카펫",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35071,
    name: "[드론] 블록케이드",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35081,
    name: "[드론] 플레어 빔",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35091,
    name: "[드론] 액티브 펄스",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35101,
    name: "[드론] 베이비 드론",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35111,
    name: "[드론] 레이드 미사일",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35141,
    name: "[드론] M143 기관총",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35702,
    name: "[아이덴티티] 하이퍼 싱크 강제 해제",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35703,
    name: "하이퍼 싱크 체크용 더미 드론스킬",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35720,
    name: "Basic Attack",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35941,
    name: "[각성기] [드론] 파이널 익스플로전",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35950,
    name: "드론 소환 (노모션)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35951,
    name: "드론 소환",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35960,
    name: "드론 명령 리액션",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35970,
    name: "드론 명령 A (노모션)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35980,
    name: "드론 명령 B (짧은 명령)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35990,
    name: "드론 명령 C (긴 명령)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35020,
    name: "Tremors",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35030,
    name: "Stand Up",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35040,
    name: "Bullet Hail",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35050,
    name: "Overcharged Battery",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35160,
    name: "High Voltage Bullet",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35170,
    name: "Strategic Fire",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35200,
    name: "Pulse Fire",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35150,
    name: "Backflip Strike",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35180,
    name: "Mobile Shot",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35182,
    name: "Mobile Shot",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35181,
    name: "Mobile Shot",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35190,
    name: "Avalanche",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35060,
    name: "Command: Carpet",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35090,
    name: "Command: Active Pulse",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35070,
    name: "Command: Blockade",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35140,
    name: "Command: M143 Machine Gun",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35080,
    name: "Command: Flare Beam",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35100,
    name: "Command: Baby Drones",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35110,
    name: "Command: Raid Missile",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35130,
    name: "Annihilation Mode",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35120,
    name: "Fiery Escape",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35210,
    name: "Energy Buster",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35730,
    name: "Thruster Move",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35740,
    name: "Stand Up",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35750,
    name: "Comet Strike",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35760,
    name: "Slugshot",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35761,
    name: "[싱크] 슬러그 샷 (연결)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35770,
    name: "Laser Blade",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35771,
    name: "[싱크] 레이저 블레이드 (연결)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35780,
    name: "Echelon Beam",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35781,
    name: "[싱크] 엑셀리온 빔 (연결)",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35790,
    name: "Surge Blow",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35800,
    name: "Crimson Breaker",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35930,
    name: "Air Strike",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35940,
    name: "Command: Final Explosion",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35711,
    name: "Command: Call Back",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35700,
    name: "Hypersync",
    class: "Scouter",
    level: 0,
  },
  {
    id: 35701,
    name: "Disable Hypersync",
    class: "Scouter",
    level: 0,
  },
  {
    id: 38060,
    name: "Spiral Flame",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38120,
    name: "AT02 Grenade",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38180,
    name: "Spiral Tracker",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38140,
    name: "Plasma Bullet",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38080,
    name: "Catastrophe",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38156,
    name: "PVP 강제 기상",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38210,
    name: "Somersault Shot",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38220,
    name: "Equilibrium",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38230,
    name: "Last Request",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38270,
    name: "Perfect Shot",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38160,
    name: "Change Stance",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38161,
    name: "Reverse Stance Switch",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38162,
    name: "Change Stance",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38163,
    name: "Change Stance",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38164,
    name: "Change Stance",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38150,
    name: "Stampede",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38155,
    name: "Stand Up",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38020,
    name: "Quick Step",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38190,
    name: "Bullet Rain",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38260,
    name: "Peacekeeper",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38100,
    name: "Meteor Stream",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38200,
    name: "Dexterous Shot",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38090,
    name: "Death Fire",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38050,
    name: "Hour of Judgment",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38040,
    name: "Dual Buckshot",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38110,
    name: "Sharpshooter",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38170,
    name: "Shotgun Rapid Fire",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38070,
    name: "Target Down",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38240,
    name: "Focused Shot",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38250,
    name: "Eye of Twilight",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 38280,
    name: "High-Caliber HE Bullet",
    class: "Gunslinger",
    level: 0,
  },
  {
    id: 39020,
    name: "Esoteric Skill: Blast Formation",
    class: "Striker",
    level: 0,
  },
  {
    id: 39070,
    name: "Sleeping Ascent Celebration",
    class: "Striker",
    level: 0,
  },
  {
    id: 39060,
    name: "Flash Heat Fang",
    class: "Striker",
    level: 0,
  },
  {
    id: 39180,
    name: "Triple Fist",
    class: "Striker",
    level: 0,
  },
  {
    id: 39110,
    name: "Esoteric Skill: Call the Wind God",
    class: "Striker",
    level: 0,
  },
  {
    id: 39030,
    name: "Esoteric Skill: Spiral Impact",
    class: "Striker",
    level: 0,
  },
  {
    id: 39130,
    name: "Phoenix Advent",
    class: "Striker",
    level: 0,
  },
  {
    id: 39160,
    name: "Sky Shattering Blow",
    class: "Striker",
    level: 0,
  },
  {
    id: 39150,
    name: "Charging Steps",
    class: "Striker",
    level: 0,
  },
  {
    id: 39190,
    name: "Moon Flash Kick",
    class: "Striker",
    level: 0,
  },
  {
    id: 39170,
    name: "Lightning Kick",
    class: "Striker",
    level: 0,
  },
  {
    id: 39155,
    name: "Stand Up",
    class: "Striker",
    level: 0,
  },
  {
    id: 39156,
    name: "Stand Up",
    class: "Striker",
    level: 0,
  },
  {
    id: 39280,
    name: "Swift Wind Kick",
    class: "Striker",
    level: 0,
  },
  {
    id: 39320,
    name: "Sweeping Kick",
    class: "Striker",
    level: 0,
  },
  {
    id: 39080,
    name: "Lightning Whisper",
    class: "Striker",
    level: 0,
  },
  {
    id: 39120,
    name: "Storm Dragon Awakening",
    class: "Striker",
    level: 0,
  },
  {
    id: 39121,
    name: "Storm Dragon Awakening",
    class: "Striker",
    level: 0,
  },
  {
    id: 39122,
    name: "Storm Dragon Awakening",
    class: "Striker",
    level: 0,
  },
  {
    id: 39290,
    name: "Violent Tiger",
    class: "Striker",
    level: 0,
  },
  {
    id: 39090,
    name: "Berserk Circle",
    class: "Striker",
    level: 0,
  },
  {
    id: 39040,
    name: "Esoteric Skill: Tiger Emerges",
    class: "Striker",
    level: 0,
  },
  {
    id: 39100,
    name: "Esoteric Skill: Lightning Tiger Strike",
    class: "Striker",
    level: 0,
  },
  {
    id: 39310,
    name: "Ultimate Skill: Nova Blast",
    class: "Striker",
    level: 0,
  },
  {
    id: 39330,
    name: "Ultimate Skill: True Heavenly Awakening",
    class: "Striker",
    level: 0,
  },
  {
    id: 0,
    name: "Bleed",
    class: "-",
    level: 0,
  },
  {
    id: 32141,
    name: "[배틀 아이템] 강철 폭탄 발사체 대미지",
    display: "[Battle Item] Destruction Bomb",
    class: "-",
    level: 0,
    icon: true,
  },
  {
    id: 32143,
    name: "[배틀 아이템] 빛나는 강철 폭탄 발사체 대미지",
    display: "[Battle Item] Splendid Destruction Bomb",
    class: "-",
    level: 0,
  },
  {
    id: 32241,
    name: "[배틀 아이템] 암흑 폭탄_발사체 대미지",
    display: "[Battle Item] Dark Grenade",
    class: "-",
    level: 0,
    icon: true,
  },
  {
    id: 32311,
    name: "[배틀 아이템] 회오리 폭탄 발사체 대미지",
    display: "[Battle Item] Whirlwind Grenade",
    class: "-",
    level: 0,
    icon: true,
  },
  {
    id: 32314,
    name: "[배틀 아이템] 빛나는 회오리 폭탄 발사체 대미지",
    display: "[Battle Item] Splendid Whirlwind Grenade",
    class: "-",
    level: 0,
  },
  {
    id: 25000,
    name: "블레이드 평타",
    display: "Basic Attack",
    class: "Deathblade",
    level: 0,
  },
  {
    id: 420610,
    name: "레이드 발탄_고공 점프 찍기",
    display: "[Raid Damage] Valtan Axe Throw",
    class: "-",
    level: 0,
  },
];
