export const skills = [
  { id: "0", name: "Bleed", class: "-", level: 0},
  { id:"10020", name: "Double Slash", class: "Warrior", level: 2 },
  { id:"10030", name: "Shoulder Charge", class: "Warrior", level: 3 },
  { id:"10040", name: "Crime Hazard", class: "Warrior", level: 2 },
  { id:"10050", name: "Assault Blade", class: "Warrior", level: 2 },
  { id:"10070", name: "Power Break", class: "Warrior", level: 7 },
  { id:"10090", name: "Finish Strike", class: "Warrior", level: 2 },
  { id:"10110", name: "Whirlwind", class: "Warrior", level: 5 },
  { id:"10120", name: "Tempest Slash", class: "Warrior", level: 9 },
  { id:"11020", name: "Gale Bird", class: "Mage", level: 0 },
  { id:"11030", name: "Crystalline Magick", class: "Mage", level: 0 },
  { id:"11040", name: "Flash Explosion", class: "Mage", level: 7 },
  { id:"11050", name: "Released Will", class: "Mage", level: 5 },
  { id:"11070", name: "Steed Charge", class: "Mage", level: 0 },
  { id:"11090", name: "Winged Spirit", class: "Mage", level: 9 },
  { id:"11100", name: "Electricity Release", class: "Mage", level: 0 },
  { id:"11110", name: "Water Elemental", class: "Mage", level: 3 },
  { id:"12020", name: "Sky Shattering Blow", class: "Martial Artist (Female)", level: 1 },
  { id:"12040", name: "Lightning Kick", class: "Martial Artist (Female)", level: 1 },
  { id:"12050", name: "Triple Fist", class: "Martial Artist (Female)", level: 1 },
  { id:"12070", name: "Flash Heat Fang", class: "Martial Artist (Female)", level: 1 },
  { id:"12090", name: "Moon Flash Kick", class: "Martial Artist (Female)", level: 5 },
  { id:"12100", name: "Seismic Strike", class: "Martial Artist (Female)", level: 3 },
  { id:"12110", name: "Phoenix Advent", class: "Martial Artist (Female)", level: 7 },
  { id:"12120", name: "Swift Wind Kick", class: "Martial Artist (Female)", level: 9 },
  { id:"13030", name: "Surprise Attack", class: "Assassin", level: 0 },
  { id:"13040", name: "Upper Slash", class: "Assassin", level: 0 },
  { id:"13050", name: "Wind Cut", class: "Assassin", level: 0 },
  { id:"13060", name: "Polestar", class: "Assassin", level: 1 },
  { id:"13070", name: "Spincutter", class: "Assassin", level: 3 },
  { id:"13080", name: "Blade Dance", class: "Assassin", level: 5 },
  { id:"13090", name: "Dark Axel", class: "Assassin", level: 7 },
  { id:"13100", name: "Death Sentence", class: "Assassin", level: 9 },
  { id:"14030", name: "Spiral Tracker", class: "Gunner (Male)", level: 0 },
  { id:"14040", name: "Enforce Execution", class: "Gunner (Male)", level: 0 },
  { id:"14050", name: "Plasma Bullet", class: "Gunner (Male)", level: 0 },
  { id:"14060", name: "Meteor Stream", class: "Gunner (Male)", level: 0 },
  { id:"14070", name: "AT01 Grenade", class: "Gunner (Male)", level: 3 },
  { id:"14080", name: "Somersault Shot", class: "Gunner (Male)", level: 5 },
  { id:"14090", name: "Dexterous Shot", class: "Gunner (Male)", level: 7 },
  { id:"14100", name: "Death Fire", class: "Gunner (Male)", level: 9 },
  { id:"16030", name: "Power Break", class: "Berserker", level: 12 },
  { id:"16050", name: "Crime Hazard", class: "Berserker", level: 10 },
  { id:"16060", name: "Shoulder Charge", class: "Berserker", level: 10 },
  { id:"16070", name: "Whirlwind", class: "Berserker", level: 10 },
  { id:"16080", name: "Hell Blade", class: "Berserker", level: 20 },
  { id:"16090", name: "Strike Wave", class: "Berserker", level: 32 },
  { id:"16100", name: "Double Slash", class: "Berserker", level: 10 },
  { id:"16110", name: "Assault Blade", class: "Berserker", level: 10 },
  { id:"16120", name: "Red Dust", class: "Berserker", level: 36 },
  { id:"16190", name: "Tempest Slash", class: "Berserker", level: 14 },
  { id:"16210", name: "Diving Slash", class: "Berserker", level: 18 },
  { id:"16220", name: "Mountain Crash", class: "Berserker", level: 16 },
  { id:"16300", name: "Finish Strike", class: "Berserker", level: 10 },
  { id:"16400", name: "Aura Blade", class: "Berserker", level: 50 },
  { id:"16500", name: "Chain Sword", class: "Berserker", level: 20 },
  { id:"16600", name: "Sword Storm", class: "Berserker", level: 40 },
  { id:"16610", name: "Wind Blade", class: "Berserker", level: 24 },
  { id:"16620", name: "Maelstrom", class: "Berserker", level: 28 },
  { id:"16700", name: "Chain of Vengeance", class: "Berserker", level: 50 },
  { id:"16710", name: "Berserk Fury", class: "Berserker", level: 50 },
  { id:"17030", name: "Sharp Gunlance", class: "Gunlancer", level: 10 },
  { id:"17040", name: "Bash", class: "Gunlancer", level: 10 },
  { id:"17050", name: "Shield Charge", class: "Gunlancer", level: 18 },
  { id:"17060", name: "Fire Bullet", class: "Gunlancer", level: 10 },
  { id:"17070", name: "Rising Gunlance", class: "Gunlancer", level: 10 },
  { id:"17080", name: "Dash Upper Fire", class: "Gunlancer", level: 10 },
  { id:"17090", name: "Hook Chain", class: "Gunlancer", level: 16 },
  { id:"17100", name: "Shield Shock", class: "Gunlancer", level: 28 },
  { id:"17110", name: "Leap Attack", class: "Gunlancer", level: 12 },
  { id:"17130", name: "Nellasia's Energy", class: "Gunlancer", level: 36 },
  { id:"17140", name: "Guardian's Thunderbolt", class: "Gunlancer", level: 14 },
  { id:"17150", name: "Shield Bash", class: "Gunlancer", level: 10 },
  { id:"17160", name: "Gunlance Shot", class: "Gunlancer", level: 40 },
  { id:"17170", name: "Guardian's Protection", class: "Gunlancer", level: 50 },
  { id:"17180", name: "Shout of Hatred", class: "Gunlancer", level: 24 },
  { id:"17190", name: "Counter Gunlance", class: "Gunlancer", level: 32 },
  { id:"17200", name: "Surge Cannon", class: "Gunlancer", level: 50 },
  { id:"17210", name: "Charged Stinger", class: "Gunlancer", level: 20 },
  { id:"17220", name: "Lance of Judgment", class: "Gunlancer", level: 50 },
  { id:"18050", name: "Heavy Crush", class: "Destroyer", level: 10 },
  { id:"18060", name: "Gravity Impact", class: "Destroyer", level: 10 },
  { id:"18070", name: "Full Swing", class: "Destroyer", level: 10 },
  { id:"18080", name: "Earth Smasher", class: "Destroyer", level: 20 },
  { id:"18090", name: "One-Man Army", class: "Destroyer", level: 18 },
  { id:"18100", name: "Neutralizer", class: "Destroyer", level: 14 },
  { id:"18110", name: "Dreadnaught", class: "Destroyer", level: 10 },
  { id:"18120", name: "Terra Break", class: "Destroyer", level: 50 },
  { id:"18130", name: "Seismic Hammer", class: "Destroyer", level: 40 },
  { id:"18140", name: "Endure Pain", class: "Destroyer", level: 50 },
  { id:"18150", name: "Earth Eater", class: "Destroyer", level: 10 },
  { id:"18160", name: "Jumping Smash", class: "Destroyer", level: 12 },
  { id:"18170", name: "Perfect Swing", class: "Destroyer", level: 28 },
  { id:"18180", name: "Power Strike", class: "Destroyer", level: 10 },
  { id:"18190", name: "Gravity Compression", class: "Destroyer", level: 36 },
  { id:"18200", name: "Gravity Force", class: "Destroyer", level: 32 },
  { id:"18210", name: "Running Crash", class: "Destroyer", level: 24 },
  { id:"18220", name: "Power Shoulder", class: "Destroyer", level: 16 },
  { id:"18230", name: "Big Bang", class: "Destroyer", level: 50 },
  { id:"19030", name: "Evoke", class: "Arcanist", level: 40 },
  { id:"19040", name: "Checkmate", class: "Arcanist", level: 16 },
  { id:"19050", name: "Dark Resurrection", class: "Arcanist", level: 32 },
  { id:"19110", name: "Prismatic Mirror", class: "Arcanist", level: 50 },
  { id:"19120", name: "Unlimited Shuffle", class: "Arcanist", level: 14 },
  { id:"19140", name: "Celestial Rain", class: "Arcanist", level: 10 },
  { id:"19150", name: "Stream of Edge", class: "Arcanist", level: 24 },
  { id:"19160", name: "Four of a Kind", class: "Arcanist", level: 12 },
  { id:"19170", name: "Quadra Accelerate", class: "Arcanist", level: 10 },
  { id:"19180", name: "Call of Destiny", class: "Arcanist", level: 10 },
  { id:"19190", name: "Spiral Edge", class: "Arcanist", level: 10 },
  { id:"19200", name: "Dancing of Spineflower", class: "Arcanist", level: 10 },
  { id:"19210", name: "Mysterious Stampede", class: "Arcanist", level: 28 },
  { id:"19230", name: "Infinity Shower", class: "Arcanist", level: 36 },
  { id:"19240", name: "Serendipity", class: "Arcanist", level: 20 },
  { id:"19260", name: "Return", class: "Arcanist", level: 20 },
  { id:"19310", name: "Secret Garden", class: "Arcanist", level: 50 },
  { id:"19320", name: "Scratch Dealer", class: "Arcanist", level: 10 },
  { id:"19330", name: "Deathbound", class: "Arcanist", level: 50 },
  { id:"20020", name: "Crystalline Magick", class: "Summoner", level: 10 },
  { id:"20030", name: "Steed Charge", class: "Summoner", level: 10 },
  { id:"20040", name: "Reine's Protection", class: "Summoner", level: 40 },
  { id:"20050", name: "Flash Explosion", class: "Summoner", level: 10 },
  { id:"20060", name: "Fleeting Gale Bird", class: "Summoner", level: 10 },
  { id:"20090", name: "Elcid", class: "Summoner", level: 12 },
  { id:"20110", name: "Pauru", class: "Summoner", level: 10 },
  { id:"20130", name: "Maririn", class: "Summoner", level: 20 },
  { id:"20160", name: "Shurdi", class: "Summoner", level: 32 },
  { id:"20180", name: "Sticky Moss Swamp", class: "Summoner", level: 18 },
  { id:"20200", name: "Released Will", class: "Summoner", level: 10 },
  { id:"20220", name: "Winged Spirit", class: "Summoner", level: 14 },
  { id:"20230", name: "Electricity Release", class: "Summoner", level: 16 },
  { id:"20240", name: "Earth Collapse", class: "Summoner", level: 20 },
  { id:"20250", name: "Water Elemental", class: "Summoner", level: 24 },
  { id:"20260", name: "Ancient Spear", class: "Summoner", level: 36 },
  { id:"20270", name: "Electric Storm", class: "Summoner", level: 28 },
  { id:"20290", name: "Kelsion", class: "Summoner", level: 50 },
  { id:"20300", name: "Bagron's Wrath", class: "Summoner", level: 50 },
  { id:"21020", name: "Sound Shock", class: "Bard", level: 10 },
  { id:"21040", name: "Conviction Core", class: "Bard", level: 10 },
  { id:"21050", name: "Sound Wave", class: "Bard", level: 10 },
  { id:"21060", name: "Dissonance", class: "Bard", level: 10 },
  { id:"21070", name: "Wind of Music", class: "Bard", level: 12 },
  { id:"21080", name: "Prelude of Storm", class: "Bard", level: 20 },
  { id:"21090", name: "Stigma", class: "Bard", level: 10 },
  { id:"21110", name: "Note Bundle", class: "Bard", level: 28 },
  { id:"21120", name: "Soundholic", class: "Bard", level: 18 },
  { id:"21150", name: "Rhythm Buckshot", class: "Bard", level: 16 },
  { id:"21160", name: "Heavenly Tune", class: "Bard", level: 24 },
  { id:"21170", name: "Sonic Vibration", class: "Bard", level: 14 },
  { id:"21180", name: "Harp of Rhythm", class: "Bard", level: 36 },
  { id:"21230", name: "Symphonia", class: "Bard", level: 50 },
  { id:"21240", name: "Prelude of Death", class: "Bard", level: 32 },
  { id:"21250", name: "Guardian Tune", class: "Bard", level: 50 },
  { id:"21260", name: "Rhapsody of Light", class: "Bard", level: 10 },
  { id:"21270", name: "March", class: "Bard", level: 40 },
  { id:"21280", name: "Oratorio", class: "Bard", level: 50 },
  { id:"22020", name: "Esoteric Skill: Blast Formation", class: "Wardancer", level: 40 },
  { id:"22030", name: "Esoteric Skill: Spiral Impact", class: "Wardancer", level: 10 },
  { id:"22040", name: "Esoteric Skill: Rising Fire Dragon", class: "Wardancer", level: 14 },
  { id:"22060", name: "Flash Heat Fang", class: "Wardancer", level: 10 },
  { id:"22070", name: "Sleeping Ascent Celebration", class: "Wardancer", level: 16 },
  { id:"22080", name: "Roar of Courage", class: "Wardancer", level: 32 },
  { id:"22090", name: "Seismic Strike", class: "Wardancer", level: 12 },
  { id:"22100", name: "Esoteric Skill: Lightning Strike", class: "Wardancer", level: 18 },
  { id:"22110", name: "Esoteric Skill: Call of the Wind God", class: "Wardancer", level: 28 },
  { id:"22120", name: "Wind's Whisper", class: "Wardancer", level: 20 },
  { id:"22130", name: "Phoenix Advent", class: "Wardancer", level: 24 },
  { id:"22160", name: "Sky Shattering Blow", class: "Wardancer", level: 10 },
  { id:"22170", name: "Lightning Kick", class: "Wardancer", level: 10 },
  { id:"22180", name: "Triple Fist", class: "Wardancer", level: 10 },
  { id:"22190", name: "Moon Flash Kick", class: "Wardancer", level: 10 },
  { id:"22280", name: "Swift Wind Kick", class: "Wardancer", level: 20 },
  { id:"22290", name: "Energy Combustion", class: "Wardancer", level: 50 },
  { id:"22310", name: "Ultimate Skill: Flash Rage Blow", class: "Wardancer", level: 50 },
  { id:"22320", name: "Sweeping Kick", class: "Wardancer", level: 36 },
  { id:"22330", name: "Ultimate Skill: Fist of Dominance", class: "Wardancer", level: 50 },
  { id:"23020", name: "Charging Blow", class: "Scrapper", level: 10 },
  { id:"23050", name: "Dragon Advent", class: "Scrapper", level: 10 },
  { id:"23060", name: "Judgment", class: "Scrapper", level: 10 },
  { id:"23070", name: "Earthquake Chain", class: "Scrapper", level: 16 },
  { id:"23080", name: "Chain of Resonance", class: "Scrapper", level: 40 },
  { id:"23090", name: "Crushing Smite", class: "Scrapper", level: 10 },
  { id:"23100", name: "Chain Destruction Fist", class: "Scrapper", level: 20 },
  { id:"23110", name: "Death Rattle", class: "Scrapper", level: 14 },
  { id:"23130", name: "Supernova", class: "Scrapper", level: 50 },
  { id:"23150", name: "Instant Hit", class: "Scrapper", level: 12 },
  { id:"23160", name: "Roundup Sweep", class: "Scrapper", level: 10 },
  { id:"23180", name: "Fierce Tiger Strike", class: "Scrapper", level: 10 },
  { id:"23200", name: "Continuous Push", class: "Scrapper", level: 24 },
  { id:"23210", name: "Critical Blow", class: "Scrapper", level: 18 },
  { id:"23220", name: "Battering Fists", class: "Scrapper", level: 20 },
  { id:"23230", name: "Iron Cannon Blow", class: "Scrapper", level: 32 },
  { id:"23240", name: "True Rising Fist", class: "Scrapper", level: 28 },
  { id:"23250", name: "Undefeated Dragon King", class: "Scrapper", level: 50 },
  { id:"23260", name: "Shredding Strike", class: "Scrapper", level: 36 },
  { id:"23270", name: "Mysterious Art: Blast of Ruination", class: "Scrapper", level: 50 },
  { id:"24040", name: "Energy Blast", class: "Soulfist", level: 40 },
  { id:"24050", name: "World Decimation", class: "Soulfist", level: 50 },
  { id:"24070", name: "Venomous Fist", class: "Soulfist", level: 10 },
  { id:"24080", name: "Lightning Palm", class: "Soulfist", level: 12 },
  { id:"24090", name: "Energy Bullet", class: "Soulfist", level: 10 },
  { id:"24110", name: "Palm Burst", class: "Soulfist", level: 18 },
  { id:"24120", name: "Heavenly Squash", class: "Soulfist", level: 14 },
  { id:"24140", name: "Crippling Barrier", class: "Soulfist", level: 32 },
  { id:"24170", name: "Magnetic Palm", class: "Soulfist", level: 10 },
  { id:"24180", name: "Pulverizing Palm", class: "Soulfist", level: 10 },
  { id:"24190", name: "Tempest Blast", class: "Soulfist", level: 20 },
  { id:"24200", name: "Shadowbreaker", class: "Soulfist", level: 24 },
  { id:"24210", name: "Merciless Pummel", class: "Soulfist", level: 36 },
  { id:"24220", name: "Bolting Crash", class: "Soulfist", level: 10 },
  { id:"24230", name: "Force Orb", class: "Soulfist", level: 28 },
  { id:"24240", name: "Flash Step", class: "Soulfist", level: 16 },
  { id:"24250", name: "Energy Release", class: "Soulfist", level: 50 },
  { id:"24260", name: "Deadly Finger", class: "Soulfist", level: 10 },
  { id:"24270", name: "Decimation Ray", class: "Soulfist", level: 50 },
  { id:"25040", name: "Surprise Attack", class: "Deathblade", level: 10 },
  { id:"25050", name: "Wind Cut", class: "Deathblade", level: 10 },
  { id:"25060", name: "Upper Slash", class: "Deathblade", level: 10 },
  { id:"25070", name: "Earth Cleaver", class: "Deathblade", level: 20 },
  { id:"25080", name: "Death Sentence", class: "Deathblade", level: 16 },
  { id:"25090", name: "Twin Shadows", class: "Deathblade", level: 18 },
  { id:"25100", name: "Blade Dance", class: "Deathblade", level: 10 },
  { id:"25110", name: "Soul Absorber", class: "Deathblade", level: 14 },
  { id:"25120", name: "Spincutter", class: "Deathblade", level: 10 },
  { id:"25130", name: "Turning Slash", class: "Deathblade", level: 28 },
  { id:"25140", name: "Moonlight Sonic", class: "Deathblade", level: 24 },
  { id:"25150", name: "Dark Axel", class: "Deathblade", level: 12 },
  { id:"25160", name: "Maelstrom", class: "Deathblade", level: 32 },
  { id:"25170", name: "Polestar", class: "Deathblade", level: 10 },
  { id:"25180", name: "Void Strike", class: "Deathblade", level: 50 },
  { id:"25190", name: "Fatal Wave", class: "Deathblade", level: 36 },
  { id:"25200", name: "Blitz Rush", class: "Deathblade", level: 40 },
  { id:"25210", name: "Head Hunt", class: "Deathblade", level: 20 },
  { id:"25300", name: "Flash Blink", class: "Deathblade", level: 50 },
  { id:"25350", name: "Blade Assault", class: "Deathblade", level: 50 },
  { id:"26050", name: "Spinning Dagger", class: "Reaper", level: 16 },
  { id:"26060", name: "Spirit Catch", class: "Reaper", level: 10 },
  { id:"26070", name: "Shadow Dot", class: "Reaper", level: 10 },
  { id:"26080", name: "Iblisto", class: "Reaper", level: 28 },
  { id:"26090", name: "Nightmare", class: "Reaper", level: 10 },
  { id:"26110", name: "Saber Stinger", class: "Reaper", level: 20 },
  { id:"26120", name: "Death Side", class: "Reaper", level: 40 },
  { id:"26140", name: "Phantom Dancer", class: "Reaper", level: 36 },
  { id:"26510", name: "Distortion", class: "Reaper", level: 10 },
  { id:"26520", name: "Blink", class: "Reaper", level: 18 },
  { id:"26550", name: "Call of the Knife", class: "Reaper", level: 10 },
  { id:"26560", name: "Black Mist", class: "Reaper", level: 24 },
  { id:"26570", name: "Shadow Trap", class: "Reaper", level: 40 },
  { id:"26600", name: "Shadow Storm", class: "Reaper", level: 12 },
  { id:"26800", name: "Last Graffiti", class: "Reaper", level: 10 },
  { id:"26810", name: "Rage Spear", class: "Reaper", level: 14 },
  { id:"26820", name: "Silent Smasher", class: "Reaper", level: 50 },
  { id:"26830", name: "Dance of Fury", class: "Reaper", level: 32 },
  { id:"26900", name: "Lunar Eclipse: Cadenza", class: "Reaper", level: 50 },
  { id:"26910", name: "Solar Eclipse: Requiem", class: "Reaper", level: 50 },
  { id:"27035", name: "Gate of Eruption", class: "Shadowhunter", level: 50 },
  { id:"27050", name: "Demonic Slash", class: "Shadowhunter", level: 10 },
  { id:"27060", name: "Nimble Cut", class: "Shadowhunter", level: 10 },
  { id:"27070", name: "Slasher", class: "Shadowhunter", level: 10 },
  { id:"27080", name: "Brutal Cross", class: "Shadowhunter", level: 18 },
  { id:"27090", name: "Demon's Grip", class: "Shadowhunter", level: 20 },
  { id:"27100", name: "Rising Claw", class: "Shadowhunter", level: 10 },
  { id:"27110", name: "Piercing Thorn", class: "Shadowhunter", level: 28 },
  { id:"27120", name: "Demon Vision", class: "Shadowhunter", level: 14 },
  { id:"27130", name: "Grind Chain", class: "Shadowhunter", level: 20 },
  { id:"27140", name: "Spinning Dive", class: "Shadowhunter", level: 10 },
  { id:"27170", name: "Howl", class: "Shadowhunter", level: 40 },
  { id:"27180", name: "Cruel Cutter", class: "Shadowhunter", level: 12 },
  { id:"27200", name: "Thrust Impact", class: "Shadowhunter", level: 16 },
  { id:"27210", name: "Demonic Clone", class: "Shadowhunter", level: 10 },
  { id:"27220", name: "Demolition", class: "Shadowhunter", level: 24 },
  { id:"27230", name: "Spinning Weapon", class: "Shadowhunter", level: 32 },
  { id:"27240", name: "Decimate", class: "Shadowhunter", level: 50 },
  { id:"27250", name: "Sharpened Cut", class: "Shadowhunter", level: 36 },
  { id:"27810", name: "Ruining Rush", class: "Shadowhunter", level: 10 },
  { id:"27820", name: "Death Claw", class: "Shadowhunter", level: 10 },
  { id:"27830", name: "Gore Bleeding", class: "Shadowhunter", level: 20 },
  { id:"27840", name: "Destruction", class: "Shadowhunter", level: 10 },
  { id:"27850", name: "Leaping Blow", class: "Shadowhunter", level: 30 },
  { id:"27860", name: "Blood Massacre", class: "Shadowhunter", level: 40 },
  { id:"27890", name: "Fallen Ruin", class: "Shadowhunter", level: 50 },
  { id:"28020", name: "Rapid Shot", class: "Sharpshooter", level: 10 },
  { id:"28030", name: "Salvo", class: "Sharpshooter", level: 16 },
  { id:"28040", name: "Atomic Arrow", class: "Sharpshooter", level: 10 },
  { id:"28050", name: "Electric Nova", class: "Sharpshooter", level: 40 },
  { id:"28060", name: "Smokescreen Arrow", class: "Sharpshooter", level: 32 },
  { id:"28070", name: "Arrow Wave", class: "Sharpshooter", level: 10 },
  { id:"28080", name: "Arrow Shower", class: "Sharpshooter", level: 10 },
  { id:"28090", name: "Charged Shot", class: "Sharpshooter", level: 14 },
  { id:"28100", name: "Evasive Fire", class: "Sharpshooter", level: 24 },
  { id:"28110", name: "Sharp Shooter", class: "Sharpshooter", level: 18 },
  { id:"28120", name: "DM-42", class: "Sharpshooter", level: 20 },
  { id:"28130", name: "Deadly Slash", class: "Sharpshooter", level: 28 },
  { id:"28140", name: "Moving Slash", class: "Sharpshooter", level: 10 },
  { id:"28150", name: "Blade Storm", class: "Sharpshooter", level: 10 },
  { id:"28190", name: "Claymore Mine", class: "Sharpshooter", level: 12 },
  { id:"28200", name: "Shadow Arrow", class: "Sharpshooter", level: 36 },
  { id:"28210", name: "Stalker", class: "Sharpshooter", level: 20 },
  { id:"28220", name: "Snipe", class: "Sharpshooter", level: 50 },
  { id:"28230", name: "Fenrir's Messenger", class: "Sharpshooter", level: 50 },
  { id:"28240", name: "Golden Eye", class: "Sharpshooter", level: 50 },
  { id:"29020", name: "Enforce Execution", class: "Deadeye", level: 10 },
  { id:"29040", name: "Sign of Apocalypse", class: "Deadeye", level: 10 },
  { id:"29050", name: "Hour of Judgment", class: "Deadeye", level: 14 },
  { id:"29060", name: "Spiral Flame", class: "Deadeye", level: 10 },
  { id:"29070", name: "Triple Explosion", class: "Deadeye", level: 20 },
  { id:"29080", name: "Catastrophe", class: "Deadeye", level: 16 },
  { id:"29090", name: "Death Fire", class: "Deadeye", level: 18 },
  { id:"29100", name: "Meteor Stream", class: "Deadeye", level: 10 },
  { id:"29110", name: "Shotgun Dominator", class: "Deadeye", level: 28 },
  { id:"29120", name: "AT02 Grenade", class: "Deadeye", level: 10 },
  { id:"29140", name: "Plasma Bullet", class: "Deadeye", level: 10 },
  { id:"29170", name: "Shotgun Rapid Fire", class: "Deadeye", level: 20 },
  { id:"29180", name: "Spiral Tracker", class: "Deadeye", level: 10 },
  { id:"29190", name: "Cruel Tracker", class: "Deadeye", level: 36 },
  { id:"29200", name: "Dexterous Shot", class: "Deadeye", level: 22 },
  { id:"29210", name: "Somersault Shot", class: "Deadeye", level: 10 },
  { id:"29220", name: "Equilibrium", class: "Deadeye", level: 12 },
  { id:"29230", name: "Last Request", class: "Deadeye", level: 40 },
  { id:"29240", name: "Aimed Shot", class: "Deadeye", level: 32 },
  { id:"29250", name: "Clay Bombardment", class: "Deadeye", level: 50 },
  { id:"29260", name: "Quick Shot", class: "Deadeye", level: 26 },
  { id:"29270", name: "Perfect Shot", class: "Deadeye", level: 50 },
  { id:"29280", name: "Bursting Flare", class: "Deadeye", level: 50 },
  { id:"30050", name: "Enhanced Shell", class: "Artillerist", level: 10 },
  { id:"30060", name: "Freeze Shell", class: "Artillerist", level: 10 },
  { id:"30070", name: "Buckshot", class: "Artillerist", level: 10 },
  { id:"30080", name: "Multiple Rocket Launcher", class: "Artillerist", level: 12 },
  { id:"30090", name: "Howitzer", class: "Artillerist", level: 10 },
  { id:"30100", name: "Summon Turret", class: "Artillerist", level: 24 },
  { id:"30110", name: "Air Raid", class: "Artillerist", level: 18 },
  { id:"30120", name: "Flamethrower", class: "Artillerist", level: 14 },
  { id:"30140", name: "Swing", class: "Artillerist", level: 16 },
  { id:"30150", name: "Jump Barrage", class: "Artillerist", level: 20 },
  { id:"30160", name: "Energy Field", class: "Artillerist", level: 50 },
  { id:"30170", name: "Gatling Gun", class: "Artillerist", level: 10 },
  { id:"30180", name: "Napalm Shot", class: "Artillerist", level: 10 },
  { id:"30190", name: "Forward Barrage", class: "Artillerist", level: 36 },
  { id:"30200", name: "Gravity Explosion", class: "Artillerist", level: 32 },
  { id:"30210", name: "Plasma Storm", class: "Artillerist", level: 28 },
  { id:"30220", name: "Homing Barrage", class: "Artillerist", level: 40 },
  { id:"30230", name: "Missile Barrage", class: "Artillerist", level: 50 },
  { id:"30250", name: "Barrage: Howitzer", class: "Artillerist", level: 10 },
  { id:"30260", name: "Barrage: Focus Fire", class: "Artillerist", level: 20 },
  { id:"30270", name: "Barrage: Energy Cannon", class: "Artillerist", level: 40 },
  { id:"30280", name: "Heavy Turret", class: "Artillerist", level: 50 },
  { id:"30290", name: "Bombardment: Impregnability", class: "Artillerist", level: 40 },
  { id:"34040", name: "Double Strike", class: "Glaivier", level: 10 },
  { id:"34050", name: "Windsplitter", class: "Glaivier", level: 28 },
  { id:"34060", name: "Stampeding Slash", class: "Glaivier", level: 10 },
  { id:"34070", name: "Wheel of Blades", class: "Glaivier", level: 18 },
  { id:"34080", name: "Flash Kick", class: "Glaivier", level: 10 },
  { id:"34090", name: "Vault", class: "Glaivier", level: 10 },
  { id:"34100", name: "Blue Dragon's Claw", class: "Glaivier", level: 24 },
  { id:"34110", name: "Half Moon Slash", class: "Glaivier", level: 12 },
  { id:"34120", name: "Chain Slash", class: "Glaivier", level: 10 },
  { id:"34130", name: "Cutting Wind", class: "Glaivier", level: 36 },
  { id:"34140", name: "Soul Cutter", class: "Glaivier", level: 10 },
  { id:"34150", name: "Raging Dragon Slash", class: "Glaivier", level: 14 },
  { id:"34160", name: "Spear Dive", class: "Glaivier", level: 20 },
  { id:"34170", name: "Shackling Blue Dragon", class: "Glaivier", level: 50 },
  { id:"34540", name: "Spiraling Spear", class: "Glaivier", level: 10 },
  { id:"34550", name: "4-Headed Dragon", class: "Glaivier", level: 10 },
  { id:"34560", name: "Thrust of Destruction", class: "Glaivier", level: 16 },
  { id:"34570", name: "Starfall Pounce", class: "Glaivier", level: 20 },
  { id:"34580", name: "Dragonscale Defense", class: "Glaivier", level: 32 },
  { id:"34590", name: "Red Dragon's Horn", class: "Glaivier", level: 40 },
  { id:"34600", name: "Yeon-Style Spear Technique: Spear Meteor", class: "Glaivier", level: 50 },
  { id:"34610", name: "Yeon-Style Spear Technique: Storming Red Dragon", class: "Glaivier", level: 50 },
  { id:"35040", name: "Bullet Hail", class: "Machinist", level: 10 },
  { id:"35050", name: "Overcharged Battery", class: "Machinist", level: 10 },
  { id:"35060", name: "Command: Carpet", class: "Machinist", level: 24 },
  { id:"35070", name: "Command: Blockade", class: "Machinist", level: 20 },
  { id:"35080", name: "Command: Flare Beam", class: "Machinist", level: 10 },
  { id:"35090", name: "Command: Active Pulse", class: "Machinist", level: 10 },
  { id:"35100", name: "Command: Baby Drones", class: "Machinist", level: 32 },
  { id:"35110", name: "Command: Raid Missile", class: "Machinist", level: 40 },
  { id:"35120", name: "Fiery Escape", class: "Machinist", level: 28 },
  { id:"35130", name: "Annihilation Mode", class: "Machinist", level: 14 },
  { id:"35140", name: "Command: M143 Machine Gun", class: "Machinist", level: 10 },
  { id:"35150", name: "Backflip Strike", class: "Machinist", level: 16 },
  { id:"35160", name: "High Voltage Bullet", class: "Machinist", level: 18 },
  { id:"35170", name: "Strategic Fire", class: "Machinist", level: 12 },
  { id:"35180", name: "Mobile Shot", class: "Machinist", level: 10 },
  { id:"35190", name: "Avalanche", class: "Machinist", level: 36 },
  { id:"35200", name: "Pulse Fire", class: "Machinist", level: 20 },
  { id:"35210", name: "Energy Buster", class: "Machinist", level: 50 },
  { id:"35750", name: "Comet Strike", class: "Machinist", level: 10 },
  { id:"35760", name: "Slugshot", class: "Machinist", level: 10 },
  { id:"35770", name: "Laser Blade", class: "Machinist", level: 10 },
  { id:"35780", name: "Echelon Beam", class: "Machinist", level: 20 },
  { id:"35790", name: "Surge Blow", class: "Machinist", level: 30 },
  { id:"35800", name: "Crimson Breaker", class: "Machinist", level: 40 },
  { id:"35930", name: "Air Strike", class: "Machinist", level: 50 },
  { id:"35940", name: "Command: Final Explosion", class: "Machinist", level: 50 },
  { id:"36030", name: "Spin Slash", class: "Paladin", level: 10 },
  { id:"36040", name: "Flash Thrust", class: "Paladin", level: 10 },
  { id:"36050", name: "Light Shock", class: "Paladin", level: 10 },
  { id:"36060", name: "Light of Judgment", class: "Paladin", level: 10 },
  { id:"36070", name: "Charge", class: "Paladin", level: 10 },
  { id:"36080", name: "Sword of Justice", class: "Paladin", level: 10 },
  { id:"36090", name: "Flash Shash", class: "Paladin", level: 12 },
  { id:"36100", name: "Holy Explosion", class: "Paladin", level: 36 },
  { id:"36110", name: "Punishment", class: "Paladin", level: 16 },
  { id:"36120", name: "Holy Area", class: "Paladin", level: 20 },
  { id:"36130", name: "Dash Slash", class: "Paladin", level: 20 },
  { id:"36140", name: "Holy Protection", class: "Paladin", level: 28 },
  { id:"36150", name: "Godsent Law", class: "Paladin", level: 14 },
  { id:"36160", name: "Executor's Sword", class: "Paladin", level: 24 },
  { id:"36170", name: "Wrath of God", class: "Paladin", level: 18 },
  { id:"36180", name: "Execution of Justice", class: "Paladin", level: 32 },
  { id:"36190", name: "Holy Sword", class: "Paladin", level: 40 },
  { id:"36200", name: "Heavenly Blessings", class: "Paladin", level: 50 },
  { id:"36210", name: "Alithanes's Judgment", class: "Paladin", level: 50 },
  { id:"36220", name: "Alithanes's Light", class: "Paladin", level: 50 },
  { id:"37200", name: "Blaze", class: "Sorceress", level: 10 },
  { id:"37210", name: "Lightning Vortex", class: "Sorceress", level: 10 },
  { id:"37220", name: "Ice Shower", class: "Sorceress", level: 18 },
  { id:"37230", name: "Inferno", class: "Sorceress", level: 12 },
  { id:"37240", name: "Energy Discharge", class: "Sorceress", level: 10 },
  { id:"37250", name: "Rime Arrow", class: "Sorceress", level: 28 },
  { id:"37260", name: "Esoteric Reaction", class: "Sorceress", level: 24 },
  { id:"37270", name: "Punishing Strike", class: "Sorceress", level: 14 },
  { id:"37280", name: "Reverse Gravity", class: "Sorceress", level: 16 },
  { id:"37290", name: "Elegian's Touch", class: "Sorceress", level: 36 },
  { id:"37300", name: "Lightning Bolt", class: "Sorceress", level: 20 },
  { id:"37310", name: "Squall", class: "Sorceress", level: 10 },
  { id:"37320", name: "Seraphic Hail", class: "Sorceress", level: 10 },
  { id:"37330", name: "Explosion", class: "Sorceress", level: 32 },
  { id:"37340", name: "Frost's Call", class: "Sorceress", level: 10 },
  { id:"37350", name: "Doomsday", class: "Sorceress", level: 50 },
  { id:"37360", name: "Enviska's Might", class: "Sorceress", level: 50 },
  { id:"37370", name: "Apocalypse Call", class: "Sorceress", level: 50 },
  { id:"38020", name: "Quick Step", class: "Gunslinger", level: 10 },
  { id:"38040", name: "Dual Buckshot", class: "Gunslinger", level: 28 },
  { id:"38050", name: "Hour of Judgment", class: "Gunslinger", level: 10 },
  { id:"38060", name: "Spiral Flame", class: "Gunslinger", level: 10 },
  { id:"38070", name: "Target Down", class: "Gunslinger", level: 50 },
  { id:"38080", name: "Catastrophe", class: "Gunslinger", level: 16 },
  { id:"38090", name: "Death Fire", class: "Gunslinger", level: 18 },
  { id:"38100", name: "Meteor Stream", class: "Gunslinger", level: 10 },
  { id:"38110", name: "Sharpshooter", class: "Gunslinger", level: 40 },
  { id:"38120", name: "AT02 Grenade", class: "Gunslinger", level: 10 },
  { id:"38140", name: "Plasma Bullet", class: "Gunslinger", level: 10 },
  { id:"38170", name: "Shotgun Rapid Fire", class: "Gunslinger", level: 14 },
  { id:"38180", name: "Spiral Tracker", class: "Gunslinger", level: 10 },
  { id:"38190", name: "Bullet Rain", class: "Gunslinger", level: 36 },
  { id:"38200", name: "Dexterous Shot", class: "Gunslinger", level: 22 },
  { id:"38210", name: "Somersault Shot", class: "Gunslinger", level: 10 },
  { id:"38220", name: "Equilibrium", class: "Gunslinger", level: 12 },
  { id:"38230", name: "Last Request", class: "Gunslinger", level: 20 },
  { id:"38240", name: "Focused Shot", class: "Gunslinger", level: 32 },
  { id:"38250", name: "Eye of Twilight", class: "Gunslinger", level: 50 },
  { id:"38260", name: "Peacekeeper", class: "Gunslinger", level: 26 },
  { id:"38270", name: "Perfect Shot", class: "Gunslinger", level: 20 },
  { id:"38280", name: "High-Caliber HE Bullet", class: "Gunslinger", level: 50 },
  { id:"39020", name: "Esoteric Skill: Blast Formation", class: "Striker", level: 40 },
  { id:"39030", name: "Esoteric Skill: Spiral Impact", class: "Striker", level: 10 },
  { id:"39040", name: "Esoteric Skill: Tiger Emerges", class: "Striker", level: 14 },
  { id:"39060", name: "Flash Heat Fang", class: "Striker", level: 20 },
  { id:"39070", name: "Sleeping Ascent Celebration", class: "Striker", level: 16 },
  { id:"39080", name: "Lightning Whisper", class: "Striker", level: 32 },
  { id:"39090", name: "Berserk Circle", class: "Striker", level: 18 },
  { id:"39100", name: "Esoteric Skill: Lightning Tiger Strike", class: "Striker", level: 50 },
  { id:"39110", name: "Esoteric Skill: Call the Wind God", class: "Striker", level: 28 },
  { id:"39120", name: "Storm Dragon Awakening", class: "Striker", level: 12 },
  { id:"39130", name: "Phoenix Advent", class: "Striker", level: 24 },
  { id:"39160", name: "Sky Shattering Blow", class: "Striker", level: 10 },
  { id:"39170", name: "Lightning Kick", class: "Striker", level: 10 },
  { id:"39180", name: "Triple Fist", class: "Striker", level: 10 },
  { id:"39190", name: "Moon Flash Kick", class: "Striker", level: 10 },
  { id:"39280", name: "Swift Wind Kick", class: "Striker", level: 20 },
  { id:"39290", name: "Violent Tiger", class: "Striker", level: 10 },
  { id:"39310", name: "Ultimate Skill: Nova Blast", class: "Striker", level: 50 },
  { id:"39320", name: "Sweeping Kick", class: "Striker", level: 36 },
  { id:"39330", name: "Ultimate Skill: True Heavenly Awakening", class: "Striker", level: 50 }
]
